export const interiors = [
    {id: 1, name: "Lunar Horizon Lounge"},
    {id: 2, name: "Stellar Observatory Room"},
    {id: 3, name: "Nebula Dream Suite"},
    {id: 4, name: "Galactic Garden Atrium"},
    {id: 5, name: "Cosmic Tranquility Spa"},
    {id: 6, name: "Aurora Borealis Ballroom"},
    {id: 7, name: "Solar Flare Café"},
    {id: 8, name: "Meteor Shower Dining Hall"},
    {id: 9, name: "Interstellar Library"},
    {id: 10, name: "Celestial Conference Center"},
    {id: 11, name: "Stardust Lounge"},
    {id: 12, name: "Eclipse Entertainment Hub"},
    {id: 13, name: "Gravity-Free Gym"},
    {id: 14, name: "Comet Cinema"},
    {id: 15, name: "Asteroid Arcade"},
    {id: 16, name: "Planetarium Patio"},
    {id: 17, name: "Black Hole Bistro"},
    {id: 18, name: "Galaxy Gourmet Restaurant"},
    {id: 19, name: "Quasar Quiet Room"},
    {id: 20, name: "Milky Way Meeting Room"},
    {id: 21, name: "Orbit Office Space"},
    {id: 22, name: "Satellite Study Room"},
    {id: 23, name: "Rocket Rooftop Terrace"},
    {id: 24, name: "Pulsar Pool"},
    {id: 25, name: "Cosmos Cocktail Bar"},
    {id: 26, name: "Space Station Lounge"},
    {id: 27, name: "Zenith Zen Garden"},
    {id: 28, name: "Lunar Lab"},
    {id: 29, name: "Martian Music Room"},
    {id: 30, name: "Venus Viewing Deck"},
    {id: 31, name: "Jupiter Jazz Club"},
    {id: 32, name: "Saturn Salon"},
    {id: 33, name: "Neptune Nightclub"},
    {id: 34, name: "Pluto Playroom"},
    {id: 35, name: "Astro Art Gallery"},
    {id: 36, name: "Meteorite Meditation Room"},
    {id: 37, name: "Solar System Study"},
    {id: 38, name: "Spacewalk Studio"},
    {id: 39, name: "Supernova Spa"},
    {id: 40, name: "Cosmic Courtyard"},
    {id: 41, name: "Galaxy Game Room"},
    {id: 42, name: "Nebula Nook"},
    {id: 43, name: "Ecliptic Event Hall"},
    {id: 44, name: "Astro Adventure Park"},
    {id: 45, name: "Starship Suite"},
    {id: 46, name: "Rocket Rec Room"},
    {id: 47, name: "Planetary Patio"},
    {id: 48, name: "Stellar Study"},
    {id: 49, name: "Intergalactic Infirmary"},
    {id: 50, name: "Astro Amphitheater"},
    {id: 51, name: "Celestial Cafe"},
    {id: 52, name: "Orbital Observatory"},
    {id: 53, name: "Lunar Lounge"},
    {id: 54, name: "Nebula Nook"},
    {id: 55, name: "Spacewalk Suite"},
    {id: 56, name: "Starlight Studio"},
    {id: 57, name: "Astro Arcade"},
    {id: 58, name: "Galaxy Gym"},
    {id: 59, name: "Nebula Nightclub"},
    {id: 60, name: "Pulsar Pool"}
];
